// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation.proto

package com.app.grpc.stubs;

public interface DeleteReservationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:reservation.DeleteReservationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();
}
