// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation.proto

package com.app.grpc.stubs;

public interface GetAllReservationsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:reservation.GetAllReservationsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .reservation.Reservation reservations = 1;</code>
   */
  java.util.List<com.app.grpc.stubs.Reservation> 
      getReservationsList();
  /**
   * <code>repeated .reservation.Reservation reservations = 1;</code>
   */
  com.app.grpc.stubs.Reservation getReservations(int index);
  /**
   * <code>repeated .reservation.Reservation reservations = 1;</code>
   */
  int getReservationsCount();
  /**
   * <code>repeated .reservation.Reservation reservations = 1;</code>
   */
  java.util.List<? extends com.app.grpc.stubs.ReservationOrBuilder> 
      getReservationsOrBuilderList();
  /**
   * <code>repeated .reservation.Reservation reservations = 1;</code>
   */
  com.app.grpc.stubs.ReservationOrBuilder getReservationsOrBuilder(
      int index);
}
