// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation.proto

package com.app.grpc.stubs;

public final class ReservationOuterClass {
  private ReservationOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_reservation_Reservation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_reservation_Reservation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_reservation_GetAllReservationsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_reservation_GetAllReservationsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_reservation_GetAllReservationsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_reservation_GetAllReservationsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_reservation_GetReservationByIdRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_reservation_GetReservationByIdRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_reservation_GetReservationByIdResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_reservation_GetReservationByIdResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_reservation_SaveReservationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_reservation_SaveReservationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_reservation_SaveReservationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_reservation_SaveReservationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_reservation_DeleteReservationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_reservation_DeleteReservationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_reservation_DeleteReservationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_reservation_DeleteReservationResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021reservation.proto\022\013reservation\"w\n\013Rese" +
      "rvation\022\n\n\002id\030\001 \001(\003\022\021\n\tdateDebut\030\002 \001(\t\022\017" +
      "\n\007dateFin\030\003 \001(\t\022\023\n\013preferences\030\004 \001(\t\022\020\n\010" +
      "clientId\030\005 \001(\003\022\021\n\tchambreId\030\006 \001(\003\"\033\n\031Get" +
      "AllReservationsRequest\"L\n\032GetAllReservat" +
      "ionsResponse\022.\n\014reservations\030\001 \003(\0132\030.res" +
      "ervation.Reservation\"\'\n\031GetReservationBy" +
      "IdRequest\022\n\n\002id\030\001 \001(\003\"K\n\032GetReservationB" +
      "yIdResponse\022-\n\013reservation\030\001 \001(\0132\030.reser" +
      "vation.Reservation\"G\n\026SaveReservationReq" +
      "uest\022-\n\013reservation\030\001 \001(\0132\030.reservation." +
      "Reservation\"H\n\027SaveReservationResponse\022-" +
      "\n\013reservation\030\001 \001(\0132\030.reservation.Reserv" +
      "ation\"&\n\030DeleteReservationRequest\022\n\n\002id\030" +
      "\001 \001(\003\"=\n\031DeleteReservationResponse\022\017\n\007su" +
      "ccess\030\001 \001(\010\022\017\n\007message\030\002 \001(\t2\260\003\n\026Reserva" +
      "tionGrpcService\022g\n\022getAllReservations\022&." +
      "reservation.GetAllReservationsRequest\032\'." +
      "reservation.GetAllReservationsResponse\"\000" +
      "\022g\n\022getReservationById\022&.reservation.Get" +
      "ReservationByIdRequest\032\'.reservation.Get" +
      "ReservationByIdResponse\"\000\022^\n\017saveReserva" +
      "tion\022#.reservation.SaveReservationReques" +
      "t\032$.reservation.SaveReservationResponse\"" +
      "\000\022d\n\021deleteReservation\022%.reservation.Del" +
      "eteReservationRequest\032&.reservation.Dele" +
      "teReservationResponse\"\000B\026\n\022com.app.grpc." +
      "stubsP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_reservation_Reservation_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_reservation_Reservation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_reservation_Reservation_descriptor,
        new java.lang.String[] { "Id", "DateDebut", "DateFin", "Preferences", "ClientId", "ChambreId", });
    internal_static_reservation_GetAllReservationsRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_reservation_GetAllReservationsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_reservation_GetAllReservationsRequest_descriptor,
        new java.lang.String[] { });
    internal_static_reservation_GetAllReservationsResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_reservation_GetAllReservationsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_reservation_GetAllReservationsResponse_descriptor,
        new java.lang.String[] { "Reservations", });
    internal_static_reservation_GetReservationByIdRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_reservation_GetReservationByIdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_reservation_GetReservationByIdRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_reservation_GetReservationByIdResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_reservation_GetReservationByIdResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_reservation_GetReservationByIdResponse_descriptor,
        new java.lang.String[] { "Reservation", });
    internal_static_reservation_SaveReservationRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_reservation_SaveReservationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_reservation_SaveReservationRequest_descriptor,
        new java.lang.String[] { "Reservation", });
    internal_static_reservation_SaveReservationResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_reservation_SaveReservationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_reservation_SaveReservationResponse_descriptor,
        new java.lang.String[] { "Reservation", });
    internal_static_reservation_DeleteReservationRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_reservation_DeleteReservationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_reservation_DeleteReservationRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_reservation_DeleteReservationResponse_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_reservation_DeleteReservationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_reservation_DeleteReservationResponse_descriptor,
        new java.lang.String[] { "Success", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
