// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation.proto

package com.app.grpc.stubs;

public interface SaveReservationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:reservation.SaveReservationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.reservation.Reservation reservation = 1;</code>
   * @return Whether the reservation field is set.
   */
  boolean hasReservation();
  /**
   * <code>.reservation.Reservation reservation = 1;</code>
   * @return The reservation.
   */
  com.app.grpc.stubs.Reservation getReservation();
  /**
   * <code>.reservation.Reservation reservation = 1;</code>
   */
  com.app.grpc.stubs.ReservationOrBuilder getReservationOrBuilder();
}
