// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation.proto

package com.app.grpc;

public interface DeleteReservationResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:reservation.DeleteReservationResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   * @return The success.
   */
  boolean getSuccess();
}
