// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation.proto

package com.app.grpc;

public final class Reservation {
  private Reservation() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_reservation_ReservationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_reservation_ReservationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_reservation_ReservationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_reservation_ReservationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_reservation_CreateReservationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_reservation_CreateReservationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_reservation_DeleteReservationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_reservation_DeleteReservationResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021reservation.proto\022\013reservation\" \n\022Rese" +
      "rvationRequest\022\n\n\002id\030\001 \001(\003\"\177\n\023Reservatio" +
      "nResponse\022\n\n\002id\030\001 \001(\003\022\023\n\013preferences\030\002 \001" +
      "(\t\022\021\n\tdateDebut\030\003 \001(\t\022\017\n\007dateFin\030\004 \001(\t\022\020" +
      "\n\010clientId\030\005 \001(\003\022\021\n\tchambreId\030\006 \001(\003\"x\n\030C" +
      "reateReservationRequest\022\023\n\013preferences\030\001" +
      " \001(\t\022\021\n\tdateDebut\030\002 \001(\t\022\017\n\007dateFin\030\003 \001(\t" +
      "\022\020\n\010clientId\030\004 \001(\003\022\021\n\tchambreId\030\005 \001(\003\",\n" +
      "\031DeleteReservationResponse\022\017\n\007success\030\001 " +
      "\001(\0102\253\002\n\022ReservationService\022U\n\016GetReserva" +
      "tion\022\037.reservation.ReservationRequest\032 ." +
      "reservation.ReservationResponse\"\000\022^\n\021Cre" +
      "ateReservation\022%.reservation.CreateReser" +
      "vationRequest\032 .reservation.ReservationR" +
      "esponse\"\000\022^\n\021DeleteReservation\022\037.reserva" +
      "tion.ReservationRequest\032&.reservation.De" +
      "leteReservationResponse\"\000B\020\n\014com.app.grp" +
      "cP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_reservation_ReservationRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_reservation_ReservationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_reservation_ReservationRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_reservation_ReservationResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_reservation_ReservationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_reservation_ReservationResponse_descriptor,
        new java.lang.String[] { "Id", "Preferences", "DateDebut", "DateFin", "ClientId", "ChambreId", });
    internal_static_reservation_CreateReservationRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_reservation_CreateReservationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_reservation_CreateReservationRequest_descriptor,
        new java.lang.String[] { "Preferences", "DateDebut", "DateFin", "ClientId", "ChambreId", });
    internal_static_reservation_DeleteReservationResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_reservation_DeleteReservationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_reservation_DeleteReservationResponse_descriptor,
        new java.lang.String[] { "Success", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
